### ISSUE TITLE
Scalability Question

### ISSUE THREAD

**Issue by mohmdelsayed** [amirgholami/adahessian#24]
Hi there,

thank you for making your code available. You used a jacobian vector product with torch.autograd.grad() to implement Hessian-free product Hz. I'm not sure how the operation using autograd isn't O(n²). It seems like it will compute the full hessian and then multiply it by the z vector. The implementation for the hessian-free product is Hv≈(∇f(x+εv)−∇f(x))/ε which requires you to do a second forward and backward passes which isn't what you have. Is there something I'm missing? Is there any computational time comparison between your algorithm and first-order optimizers?

Moreover, you mentioned that backpropagate g^Tz, but I don't see that in the code. I think autograd doesn't support backpropagating more than grads at the moment and there is no hessian propagation in PyTorch.

Thank you.

**Comment by amirgholami** [comment]
Hi Mohamed,

Thank you for reaching out. The reason is it is not O(n2) is because we use the so-called matrix free method that only computes the action of the Hessian to a given vector. That is we do not need to first form the Hessian matrix and then multiply it with a vector. You see the formula in equation 2 in the PyHessian paper. 

This is also where the operations haven in the code:
https://github.com/amirgholami/PyHessian/blob/master/pyhessian/hessian.py#L96-#L100



Cheers,
